version: "3.9"

services:
  nextjs:
    restart: always
    build:
        context: ./nextjs
        dockerfile: Dockerfile
    container_name: frontend_image
    volumes:
        - ./nextjs:/app
        - /app/node_modules
    ports:
        - 3000:3000
    depends_on:
        - fauna_db_api
    networks:
        - express-api
    environment:
      API_BASE_URL: http://nextjs
      API_PORT: 4000

  fauna_db_api:
    restart: always
    build:
      context: ./fauna_db_api/fauna_db_api
      dockerfile: Dockerfile
    container_name: server_image
    ports:
      - 4000:4000
    volumes:
      - ./fauna_db_api:/app
    networks: 
      - express-api
    environment:      
      API_BASE_URL: http://fauna_db_api
      API_PORT: 4000
      fauna_db_api: ${FAUNA_DB_API}

  nginx:
    restart: always
    build:
        context: ./nginx
        dockerfile: Dockerfile
    ports:
        - 8080:80
    depends_on:
        - fauna_db_api
        - nextjs
    networks:
        - express-api

networks:
  express-api:
    driver: bridge
